### ISSUE TITLE
Multimeasure rests

### ISSUE THREAD

**Issue by remcohh** [paulrosen/abcjs#24] opened 2014-11-10 09:33 UTC
Are multi-measure rests (Z) implementend?
I see code dealing with this but they don't seem to work. Is this still something in progress?

**Comment by paulrosen** [comment] 2015-12-05 05:06
It looks like a bug. I'll look at it.

**Comment by libertychisasuro** [comment] 2016-06-14 12:02
Any updates on support for multi-measure rests?

**Comment by paulrosen** [comment] 2018-02-27 03:43
Will be in version 3.3.4

**Closed** 2018-02-27 04:00 UTC

**Comment by WolfgangDreier** [comment] 2020-07-27 15:52
Z (multimeasure rests) work for the printed output in the current version of abcjs, but don't seem to work for the midifile. 

X: 1
M: 3/4     
L: 1/4     
D D D D | Z | D D D | Z | D D D     

produces 

![grafik](https://user-images.githubusercontent.com/68856333/88559499-2de04680-d02d-11ea-9399-62d9d1c6fa84.png)
which looks okay, but the midiplayer will always play four quarter notes for the two multi measure rests (even if M:5/4 or M:2/4). 

[Here](https://www.volksmusikdatenbank.at/PSI/redirect.psi?f_search=!26sessid=---!26strsearch=IDU=1A898D04-380-0004C-0000646A-1A89299D!26pool=VLWX!26fil_select=TIT!26) is another example, a transcription of Pommer: 444 Jodler und Juchezer, where we want to reproduce the original source as far as possible (and so we don't want to replace Z with z3 (when L:1/4)).
