### ISSUE TITLE
Multimeasure rests (Z) still don't seem to work

### ISSUE THREAD

**Issue by WolfgangDreier** [paulrosen/abcjs#494] opened 2020-07-28 13:37 UTC
Z (multimeasure rests) don't seem to work for the printed output in the current version of abcjs (I tried https://www.abcjs.net/abcjs-editor.html): 

X: 1
M: 3/4
L: 1/4
K: C
V:1
z3|ABC|DEF|
V:2
Z |ABC|DEF|

produces: 

![grafik](https://user-images.githubusercontent.com/68856333/88640206-f5d51400-d0bd-11ea-85ee-34989634ccb3.png)

And also don't seem to work for the midifile:

X: 1
M: 3/4     
L: 1/4     
D D D D | Z | D D D | Z | D D D     

produces 

![grafik](https://user-images.githubusercontent.com/68856333/88559499-2de04680-d02d-11ea-9399-62d9d1c6fa84.png)
which looks okay (as it is single voice), but the midiplayer will always play four quarter notes silence for the two multi measure rests (even if M:5/4 or M:2/4). 

[Here](https://www.volksmusikdatenbank.at/PSI/redirect.psi?f_search=!26sessid=---!26strsearch=IDU=1A898D04-380-0004C-0000646A-1A89299D!26pool=VLWX!26fil_select=TIT!26) is another example, a transcription of Pommer: 444 Jodler und Juchezer, where we want to reproduce the original source as far as possible (and so we don't want to replace Z with z3 (when L:1/4)).

_Originally posted by @WolfgangDreier in https://github.com/paulrosen/abcjs/issues/24#issuecomment-664479325_

**Comment by paulrosen** [comment] 2020-08-02 00:39
Thanks for the bug report. I'll look into this - I think both of these bugs are caused by the multimeasure rest not respecting the time signature. It will be fixed in 6.0.0-beta.14.

**Closed** 2020-08-08 17:01 UTC
