### ISSUE TITLE
Changing meter from what ever meter to 3/4 will triple the speed in audio playback

### ISSUE THREAD

**Issue by musikboden** [paulrosen/abcjs#372] opened 2020-04-14 06:24 UTC
Hi!
I'm a new ABC user and I'm building an "A Prima Vista" application for my music students.
I've noticed that if I have the same tempo and change the meter in 
`"M: 4/4\n"`
from any meter to 3/4 it will triple the audio playback speed.
I've tried with this meters ( 2/4, 4/4, 5/8, 6/8, 7/8, 9/8) and they will play in tempo but not 3/4.
I'm using the "full synth" example with "abcjs_basic_6.0.0-beta.8-min.js"
If this is a bug, is there a workaround for having the right tempo with any kind of meter?

Cheers and thank you for doing a great job with this! / Ulrik

**Comment by ThorsenRune** [comment] 2020-04-14 11:10
Confirm. Taking editor-synth.html and modifying to 3/4 will play at incredible speed. It's a new bug.

**Comment by musikboden** [comment] 2020-04-14 12:10
This is an example where choosing 3/4 will increase the speed a lot.
http://www.musikboden.se/avista.html

**Comment by ThorsenRune** [comment] 2020-04-14 12:22
Myket fint side du har der. 
There is also another problem: If I the page is not maximized it higlihgts the wrong notes. E.g I click last note over tango and it highlights previous bar
![image](https://user-images.githubusercontent.com/6916927/79224433-5a47cc80-7e5b-11ea-9845-36e1109bcd1d.png)

**Comment by musikboden** [comment] 2020-04-14 12:51
Ok, I see what I can do about it, I guess it has to do with my html formatting, thanks!

**Comment by ThorsenRune** [comment] 2020-04-14 15:16
I think its the ABCJS because I have the same problem.

**Comment by musikboden** [comment] 2020-04-14 15:45
Yes, you're right, I checked and it is the ABCJS.

**Comment by ThorsenRune** [comment] 2020-04-16 06:25
Found that the responsive parameter to be the culprit.  Set it false. I have a workaround that I can post if you are interested.

**Comment by musikboden** [comment] 2020-04-16 06:33
> Found that the responsive parameter to be the culprit. Set it false. I have a workaround that I can post if you are interested.

Yes please, I'm interested in a work around. 👍

**Comment by ThorsenRune** [comment] 2020-04-16 12:33
Re.responsive in the abc_renderer.js I have added a parameter 'fit' for responsive and for me it does the job.
	if (responsive === 'resize') {
		this.paper.setResponsiveWidth(w, h);
	} else {
		parentStyles.width = "";
		parentStyles.height = h + "px";
		if (scale < 1) {
			parentStyles.width = w + "px";
			this.paper.setSize(w / scale, h / scale);
		} else
			this.paper.setSize(w, h);
	}
	this.paper.setScale(scale);
	if (responsive === 'fit') {
		var f=this.paper.svg.parentElement.offsetWidth/w;		//Fraction of full width
		this.paper.setScale(scale*f);
	}
	this.paper.setParentStyles(parentStyles);

**Comment by ThorsenRune** [comment] 2020-04-16 12:34
next issue is back to the 3/4 speed. Any news?

**Comment by paulrosen** [comment] 2020-04-16 13:26
I have an idea about what is causing the 3/4 speed problem and will see what I can do this weekend.

**Comment by paulrosen** [comment] 2020-04-16 13:31
I just checked your site and I'm not sure what the selection issue was. Did you already apply that change? If I understood what the problem was I would be willing to add the "fit" parameter to the release.

**Comment by ThorsenRune** [comment] 2020-04-16 15:12
Hi Paul, what site?  if you check musikboden's site the problem is when the window is resized. Then the selection is off. I think its because it gets its cordinates relative to the screen rather than the viewport. 
As of 3/4 if you give me a hint of where to look I can maybe help?
Cheers

**Comment by paulrosen** [comment] 2020-04-16 17:26
My first guess is `abc_tune.js` in the function `getBeatLength`. That is where I figure out if the meter is compound or not.

**Comment by paulrosen** [comment] 2020-04-16 17:28
I see the selection problem now.

**Comment by musikboden** [comment] 2020-04-16 20:46
> Re.responsive in the abc_renderer.js I have added a parameter 'fit' for responsive and for me it does the job.
> if (responsive === 'resize') {
> this.paper.setResponsiveWidth(w, h);
> } else {
> parentStyles.width = "";
> parentStyles.height = h + "px";
> if (scale < 1) {
> parentStyles.width = w + "px";
> this.paper.setSize(w / scale, h / scale);
> } else
> this.paper.setSize(w, h);
> }
> this.paper.setScale(scale);
> if (responsive === 'fit') {
> var f=this.paper.svg.parentElement.offsetWidth/w; //Fraction of full width
> this.paper.setScale(scale*f);
> }
> this.paper.setParentStyles(parentStyles);

Oh, I thought it was a workaround for the tempo issue in 3/4, but this is good as well, thank you!

**Comment by ThorsenRune** [comment] 2020-04-16 21:13
RE: meter length problem:
Thanks Paul.
adding to getBeatLength solves the problem 
` if` (num === 6 && den === 8) return 3/8;
if (num === 3 && den === 4) return 3/4;  //New code
```

**Comment by paulrosen** [comment] 2020-04-19 21:32
Do you want to do a pull request or should I just add that myself?

**Comment by musikboden** [comment] 2020-05-02 11:17
> Do you want to do a pull request or should I just add that myself?

If you're asking me, I don't know how to do it :) Sorry

**Comment by paulrosen** [comment] 2020-05-17 23:32
Will be fixed in 6.0.0-beta.10

**Comment by musikboden** [comment] 2020-05-18 05:19
Nice, thank you!

**Closed** 2020-05-25 18:52 UTC

**Comment by musikboden** [comment] 2020-05-26 20:49
Thank you, now 3/4 is working fine!

**Comment by ThorsenRune** [comment] 2020-05-28 12:36
> RE: meter length problem:
> Thanks Paul.
> adding to getBeatLength solves the problem
> ` if` (num === 6 && den === 8) return 3/8;
> if (num === 3 && den === 4) return 3/4; //New code

Hi Paul, did you implement this in beta.10 ? I cant find it or maybe you solved it in another way?

**Comment by ThorsenRune** [comment] 2020-05-28 12:37
Sorry found it in getBeatsPerMeasure-Its a bit hackish. May I ask why you put it here?
