### ISSUE TITLE
parse midi file

### ISSUE THREAD

**Issue by zhaokewei** [paulrosen/abcjs#208] opened 2019-04-01 03:21 UTC
Hello, thanks for your great project! I want to ask if this library can load and parse midi file, I want to transform midi file to standard music notation in a browser, thank you.

**Comment by straight-shoota** [comment] 2019-04-01 07:39
Duplicate of #204

**Comment by zhaokewei** [comment] 2019-04-29 02:20
Duplicate of #204

**Closed** 2019-04-29 02:20 UTC
