### ISSUE TITLE
get note name play while animate

### ISSUE THREAD

**Issue by steub** [paulrosen/abcjs#149] opened 2018-04-12 06:53 UTC
Bonjour,

First i really thank you for this awesome javascript library and for the time you passed on it.

I have an issue on the animation. I tested on this link (https://configurator.abcjs.net/audio) the animate part to get note name while the animation is started just like you said :

`animate: {
               listener: function(lastRange, currentRange, context){ 
                                        colorRange(lastRange, "#000000");
                                        colorRange(currentRange, "#3D9AFC"); 
                                        var startChar = currentRange.startChar;
                                        var endChar = currentRange.endChar;`

etc.

This works fine with one or multiple voices but only display the first voice when notes are play in the same time on multiple voice.

exemple : 
![image](https://user-images.githubusercontent.com/38310214/38660684-6988b17e-3e2e-11e8-9a06-5ac062a54912.png)

In blue the notes display in red, notes which are not. When i console.log() the currentRange, there is only the first startchar and endchar.

Can you help me ?
Thank you in advance
Sébastien

**Comment by paulrosen** [comment] 2018-04-12 12:14
First, can you post the exact ABC string you used?

If I go to https://configurator.abcjs.net/audio/ and pick `Index of the tune = 2`, I see similar piano music to what you posted. When I play the tune with animation on, I see all the notes highlighted normally.

However, you're right that it is only sending back startChar and endChar for the first staff.

So, it sounds like you are reporting two separate bugs:

1) In the callback, `currentRange` does not include all of the notes. (This one I can't reproduce until I see your ABC string.)

2) In the callback, `startChar` and `endChar` should return more than one set of values if there is more than one voice. (I can confirm this bug.)

**Comment by steub** [comment] 2018-04-12 12:28
Re, thank you for your reply.

I don't have problem with notes are not display. The currentRange array is really fine.
It's only the point 2 you have mentionned above : startChar and endChar return only set of values.

Sorry, i wasn't very clear in my explanations.

In my exemple, the blue circles are show in startChar and endChar parameters not the red just below it.

Thanks.

**Comment by paulrosen** [comment] 2018-10-04 20:47
For backwards compatibility, I've left the current `startChar` and `endChar` alone, but I added `startCharArray` and `endCharArray` to have the array of notes.

This will be in version 5.3.0.

**Closed** 2018-10-05 01:10 UTC

**Comment by steub** [comment] 2018-12-03 08:47
Sorry Paul for my late answer,

I will test that ! thanks for your job :)

**Comment by jepcolombia** [comment] 2018-12-13 23:55
Hi Paul,
Could you please help me with colorRange () function in above conversation. Iam trying to do the "bouncing ball" effect on the visual music, but since iam a beginer have not yet been able to figure out how. Do not know what instruccion to put in the animate callback function...sorry to bother you.

Thank you very much in advance!!

**Comment by paulrosen** [comment] 2018-12-14 00:38
What do you have so far? Do you have a web page and are calling `renderAbc()` and seeing the music rendered? If you post that code I can add the `animate` parameter to it. You can also look at this page: https://configurator.abcjs.net/audio that is my attempt at a tutorial on how to use this library.

**Comment by jepcolombia** [comment] 2018-12-14 01:14
Thank you very much for your quick answer. Yes a have the music rendered using your basic-midi example, i Also do a console.log to currentRange an lastRange i can see their content but do not know to apply color to those objects, and how to select the fields needed.
I see the help with the configurator but could not figured out how to set color to last and current played note .
colorRange Function  above seems to make what i need but code is not anywhere.

Sorry for my English

**Comment by paulrosen** [comment] 2018-12-14 14:01
This is the code from the configurator. It uses ES6 syntax, so you might have to tweak it if you aren't using babel:
```
colorRange(range, color) {
  if (range && range.elements) { // At the beginning the old node is null, at the end, the new node is null.
    range.elements.forEach(function (set) {
      set.forEach(function (item) {
        item.setAttribute("fill", color);
      });
    });
  }
},
```

And it is called here:
```
animateCallback(lastRange, currentRange, context) {
  this.colorRange(lastRange, "#000000"); // Set the old note back to black.
  this.colorRange(currentRange, "#3D9AFC"); // Set the currently sounding note to blue.
```
