### ISSUE TITLE
GET https://paulrosen.github.io/midi-js-soundfonts/FluidR3_GM/acoustic_grand_piano-ogg.js net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by caseywatts** [paulrosen/abcjs#263] opened 2019-10-18 22:10 UTC
I can't get the MIDI player working in Chrome. I have issues both locally and on the "Basic demo". This is the error I get:
![image](https://user-images.githubusercontent.com/273653/67131270-f86f1880-f1d1-11e9-82cc-2e0fe18ccdaf.png)

"Basic" demo link for convenience: https://www.abcjs.net/abcjs-basic.html

I suspect this may be caused by a Chrome security update. The best way to get around this might be to bundle this ogg js file into abcjs directly?

**Comment by paulrosen** [comment] 2019-10-19 07:41
I just tried in Chrome 77.0.3865.120 and it works for me. (on both mac and pc). From googling around, I get the suggestion that it might be caused by an extension that you have installed, like AdBlock. Can you disable your extensions one by one to see if that is the case? I can then install that extension and see what I can do.

And - what device are you seeing this on?

**Comment by caseywatts** [comment] 2019-10-20 16:33
aha it was AdBlock! https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom/related

I'm on a Windows 10 machine today.

**Comment by caseywatts** [comment] 2019-10-20 16:40
There's an AdBlock panel in the Chrome Inspector. It looks like any xmlhttprequest (like this) requests to github.io are blocked by AdBlock by default.
![image](https://user-images.githubusercontent.com/273653/67162866-82d08d00-f336-11e9-9996-8dd889cb7282.png)

**Comment by paulrosen** [comment] 2019-10-21 09:19
I'm moving to a better way to do audio - I haven't gotten the demo up yet, but I will soon. I think the new demo won't have that issue.

**Comment by paulrosen** [comment] 2019-10-21 13:11
I changed the demo on abcjs to use the new audio - let me know if that is working for you.

**Comment by caseywatts** [comment] 2019-10-25 23:04
I see that it's different, but these are being blocked too:
![image](https://user-images.githubusercontent.com/273653/67609340-37fdad80-f75a-11e9-9eb9-c9cd52ebfb5c.png)

**Comment by paulrosen** [comment] 2019-11-03 20:52
I don't know what to do about this - if this were included in abcjs it would make the bundle really large and most people want just a small number of notes. I wonder if there is a way to tell adblock that these are friendly.

**Comment by paulrosen** [comment] 2019-11-03 21:20
I left a request to unblock: https://github.com/hoshsadiq/adblock-nocoin-list/issues/394

**Comment by paulrosen** [comment] 2019-11-04 00:38
Thanks for letting me know! It looks like they fixed the issue.

**Closed by paulrosen** 2019-11-04 00:38 UTC

**Comment by caseywatts** [comment] 2019-11-07 00:36
this is a great outcome! Really cool that we can add things to their list, great find.

Thank you for looking into this and finding a solution! 🎉
