### ISSUE TITLE
Feature request: support for text annotations in redefinable symbols

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#435] opened 2020-06-11 15:18 UTC
This might be a handy feature.

From the [ABC doc](http://abcnotation.com/wiki/abc:standard:v2.2#redefinable_symbols):

>Example: To print a plus sign over notes, define p as follows and use it before the required notes:
>
>`U: p = "^+"`

--------

More info:

Here is my use case. For some sections of music, I want to add slashes to signify beats (as discussed in #422).

![out](https://user-images.githubusercontent.com/2993720/84452291-682f8900-ac23-11ea-8bff-3512286894bf.jpg)

I could use `!style=rhythm! B0`:

```
U:s=!style=rhythm!
%
% inserting `x8 &` to facilitate chord playback
"Bb" x8 & sB0 sB0 sB0 sB0 | "F7" x8 & sB0 sB0 sB0 sB0 |
```

But that would leave unwanted audio artifacts.

I could transpose the `B0` to an unplayable note:

```
U:s=!style=rhythm!
%
V:1 transpose=-144
"Bb" x8 & sB0 sB0 sB0 sB0 | "F7" x8 & sB0 sB0 sB0 sB0 |
```

But that feels a little hacky. So here's my current solution:

```
%%annotationfont Courier New italic bold 12
%
"F7" "@0,-13/"x2 "@0,-13/"x2 "@0,-13/"x2 "@0,-13/"x2 | \
"Bb" "@0,-13/"x2 "@0,-13/"x2 "@0,-13/"x2 "@0,-13/"x2 |
```

I like the visuals of this score, and it plays back well. But this would help clean up the code:

```
%%annotationfont Courier New italic bold 12
U: s = "@0,-13/"
%
"F7" sx2 sx2 sx2 sx2 | "Bb" sx2 sx2 sx2 sx2 |
```

What do you think?

**Comment by paulrosen** [comment] 2020-06-13 21:43
Not sure. I think that if the note style is rhythm then it should automatically translate it to a chord. But how would that interact with the already existing guitar chords (which are pretty much mandatory with the rhythm notation for it to make any sense). Perhaps where that exists the generated chord should always be a "chick" so leave out the "boom".

**Comment by chrisfargen** [comment] 2020-06-14 03:25
Sorry, I think I muddied the waters with too many extraneous details.

Basically, on the topic of [redefinable symbols](http://abcnotation.com/wiki/abc:standard:v2.1#redefinable_symbols), abcjs supports code like this:

```
U: T = !trill!
Tc8 |
```

But if you try code like this:

```
U: T = "^hello"
Tc8 |
```

you get this error code:

![2020-06-13-232445_545x216_scrot](https://user-images.githubusercontent.com/2993720/84583948-1cb8de80-adcd-11ea-8b8c-89fe6c776eb5.png)

**Comment by paulrosen** [comment] 2020-06-14 23:30
That use of macros hasn't been implemented yet.

However, in the latest commits, I fixed the playback of `B0` in this case. That is, if the note head is "rhythm" then the appropriate chord is played. That will be in 6.0.0-beta.11

**Comment by chrisfargen** [comment] 2020-06-15 14:19
Alright, thanks Paul.

**Closed** 2020-06-17 07:49 UTC

**Comment by chrisfargen** [comment] 2020-06-18 21:29
Paul, I appreciate your looking into this issue and fixing the loud B note that played as a result of using the slash symbol invoked via `!style=rhythm! B0`. However, I wanted to leave some feedback from the perspective of using `!style=rhythm! B0` for _slash notation)_ (in contrast to rhythmic notation) in chord charts and lead sheets for jazz.

From the Wikipedia article for [Chord chart / Slash notation](https://en.wikipedia.org/wiki/Chord_chart#Slash_notation):

> Slash notation is a form of purposefully vague musical notation which indicates or requires that an accompaniment player or players improvise their own rhythm pattern or comp according to the chord symbol given above the staff. On the staff a slash is placed on each beat (so that there are four slashes per measure in 4/4 time).
>
> Slash notation and rhythmic notation may both be used in the same piece...

In slash notation, the slash is not a rhythmic prescription, but rather it gives the player license to improvise rhythmic and/or melodic material. The slashes are really just meant to fill space. Therefore, at least for slash notation, interpreting slashes as _rests_ would be preferable to interpreting slashes as "chick". This way, the "boom chick boom2 chick" pattern (which sounds better than "chick chick chick chick") would be consistent across the whole tune, whether or not slashes are present.

To illustrate, here's a tune:

```
X: 182
T: Them there eyes
T: QHCF version
C: Pinkard, Tauber & Tracy
Z: ABC transcription by Chris Fargen, <chrisfargen@gmail.com>
M: 4/4
L: 1/8
R: swing
K: Dmaj
Q: 1/4=200
U: s=!style=rhythm! % sB0 = slash
%
P: A
"D" a2 fe de f2 | a2 fe de f2 | "C#7" b4 b3 b- | b4 z4 |
"D" a2 fe de f2 | a2 fe de f2 | "E-7" b4 b3 b- | "A7" b4 z4 |
"F#7" sB0 sB0 sB0 sB0 | sB0 sB0 sB0 sB0 | "B-" sB0 sB0 sB0 sB0 | sB0 sB0 sB0 sB0 |
"E7" sB0 sB0 sB0 sB0 | sB0 sB0 sB0 sB0 | "A7" sB0 sB0 sB0 sB0 | sB0 sB0 sB0 sB0 ||
P: B
"D" a2 fe de f2 | a2 fe de f2 | "C#7" b4 b3 b- | b4 z4 |
"D7" z2 d'2 d'2 d'2 | d'2 b2 a2 f2 | "G" e8- | e8 |
"G" sB0 sB0 sB0 sB0 | "G#°7" sB0 sB0 sB0 sB0 | "D" sB0 sB0 sB0 sB0 | "B7" sB0 sB0 sB0 sB0 |
"E7" sB0 sB0 sB0 sB0 | "A7" sB0 sB0 sB0 sB0 | "D" sB0 sB0 "D#°7" sB0 sB0 | "E-7" sB0 sB0 "A7" sB0 sB0 |]
```

And here's the audio playback in 6.0.0-beta.12 (zipped because github):

[them-there-eyes.mp3.zip](https://github.com/paulrosen/abcjs/files/4801243/them-there-eyes.mp3.zip)

However, I understand that the new functionality makes sense in the context of rhythmic notation, which may be present alongside slash notation. For that reason, maybe there should be an additional slash symbol that renders as a 1/4-note rest in the audio playback? Something like `!/!`?

**Comment by MisterY** [comment] 2021-02-08 23:03
The last comment is accurate. For drumset, the slash notation means just "play time" without any specifics.
Rhythmic notation, however, indicates a specific phrase to be played, usually by the whole band or just the rhythm section.
So, I support having a distinction between the two but the issue is closed. :)
