### ISSUE TITLE
Issue with `y` spacer in triplet 

### ISSUE THREAD

**Issue by chrisfargen** [paulrosen/abcjs#519] opened 2020-09-03 20:13 UTC
Here's how it's supposed to sound:

```
X:
K: F
%%score (L R)
V: L
d2 d2 (3 c2 A2 G2 | F8 |
V: R
G2 G2 E2 E2 | D8 |
```

Here's what happens with a `y` spacer.

```
X:
K: F
%%score (L R)
V: L
d2 d2 (3 c2 y A2 G2 | F8 |
V: R
G2 G2 E2 E2 | D8 |
```

**Comment by paulrosen** [comment] 2020-09-05 15:27
I can reproduce. It will be fixed soon.

**Comment by paulrosen** [comment] 2020-09-05 16:07
This will be fixed in beta.16. There is an odd effect here: you need to put spacers in all voices to keep things lined up, but since the spacer in the triplet is not the same length you have to do this:
```
X:1
T: spacer-in-triplet
Q:1/4=40
K: F
%%score (L R)
V: L
d2 d2 (3 c2 y A2 G2 | F8 |
V: R
G2 G2 E2 y2/3 E2 | D8 |
```
Notice the `y2/3` to give the spacer the same length outside of a triplet.

Also note that the above WON'T work until beta.16

**Comment by chrisfargen** [comment] 2020-09-05 16:31
Thanks for looking into it. I see the issue you describe in the multi-voice context.

In light of your example, it might be nice if it were not a requirement to keep spacer values the same in all voices to obtain proper alignment. It seems like maintaining sync between all voices should take precedence over cosmetic markup.

As an analogy, the example below contains text in only one voice, yet notes maintain proper vertical alignment.

```
X:1
T:
Q:1/4=100
K: F
%%score (L R)
V: L
">this text moves;all voices rightward"c4 c4 |
V: R
C4 C4 |
```

**Comment by paulrosen** [comment] 2020-09-10 03:08
For not needing it in all voices, I'm not sure. One disadvantage of the ABC format is that the user has to be careful to make sure all voices are in parallel.

Fixed in beta.16

**Closed by paulrosen** 2020-09-10 03:08 UTC
