### ISSUE TITLE
Random slurs not being rendered with altered staff width.

### ISSUE THREAD

**Issue by LupusOssorum** [paulrosen/abcjs#104] opened 2017-08-07 06:02 UTC
When rendering the tune below with a staff width of 1000 most of the slurs are not rendered (The second and third notes should be slured).  

"""
X:1
T:Arnold
P:CM
C:Samuel Arnold, 1740-1802
O:
M:3/4
L:1/4
K:Dmaj
%%score ( s0 a0) ( t0 b0)
V:s0 clef= treble
V:a0 clef= treble
V:t0 clef= bass
V:b0 clef= bass
[V:s0] A  | (AF)A | (GE)G  | (FG)F    | E2   || E   | (FG)A      | (B/>A/G)F       | E2   ||
[V:a0] F  | (FD)F | (EC)E  | (DE)D    | C2   || C   | D2D        | D2D             | C2   ||
[V:t0] A, | A,2A, | A,2A,  | A,2A,    | A,2  || A,  | (A,G,)F,   | (G,/2>A,/2B,)A, | A,2  ||
[V:b0] D, | D,2D, | A,,2C, | (D,C,)D, | A,,2 || A,, | (D,B,,)A,, | G,,2D,          | A,,2 ||
[V:s0] A  | (B/>c/d)B       | (AF)A    | (B/>c/d)B       | A2  || A  | (Bc)d/A/ | (GF)E     | D2  |]
[V:a0] D  | D2D             | D2D      | D2D             | D2  || D  | (DG)F    | (ED)C     | D2  |]
[V:t0] A, | (G,/2>A,/2B,)G, | A,2F,    | (G,/2>A,/2B,)G, | F,2 || A, | G,2A,    | (B,A,)G,  | F,2 |]
[V:b0] F, | G,2G,           | (F,D,)D, | G,2G,,          | D,2 || F, | (G,E,)D, | (G,A,)A,, | D,2 |]
"""

**Comment by paulrosen** [comment] 2017-11-15 19:49
I was not able to reproduce this. It might have been fixed in version 3.2.0, or I might not have the right conditions. Would you let me know if this is still a problem?

**Comment by paulrosen** [comment] 2018-01-15 22:03
Since I can't reproduce this, I'm closing the issue. Please reopen if it is still a problem.

**Closed by paulrosen** 2018-01-15 22:03 UTC
